services:
  - type: web
    name: fastcampus-crawler-api
    env: python
    plan: free
    buildCommand: chmod +x install_chrome.sh && ./install_chrome.sh && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver